### ISSUE TITLE
Extract annotations plugin into feature branch + reallocate utility / convenience functions

### ISSUE THREAD

**Issue by danielweck** [readium/readium-shared-js#201]
https://github.com/readium/readium-shared-js/tree/develop/plugins/annotations

https://github.com/readium/readium-shared-js/blob/develop/plugins/annotations/annotations_module.js#L683

**Comment by danielweck** [comment]
Utility function fix: https://github.com/readium/readium-shared-js/issues/147

**Comment by jdempcy** [comment]
I'm a software developer at Bluefire Productions. We make extensive use of the annotations plugin. I'd like to be involved in the ongoing work to extract CFI functionality out of the annotations plugin as well as work towards fixing any performance issues we've encountered.

**Comment by Bluefire-BuildMaster** [comment]
I am not entirely sure what the relationship is between @JCCR 's testing of @dmitrym0 's prefetch code and the memory leak that seemed to come from the Annotation's module.  Is there a plan to pursue this further or is removing annotations the extent of the plan?

**Comment by JCCR** [comment]
@Bluefire-BuildMaster 
There isn't a strong relationship. @dmitrym0 's prefetching code allowed me to benchmark and test the scenario of when an iframe is unloaded and a new one created when switching from one spine item to the next. You could replicate my findings without the prefetching, it just doesn't have the same "impact". From what I observed the memory leaks were happening because Backbone was keeping references to the iframes, DOM nodes, and other objects and they were not being cleaned up by the GC. The only place where we use backbone is in the annotations module.

**Comment by danielweck** [comment]
Let's not forget to rename the CSS classes that are used to highlight / etc.
See: https://github.com/readium/readium-shared-js/issues/203

**Comment by Bluefire-BuildMaster** [comment]
Thank you, @JCCR.  For those of us that use the annotations module, is there a plan to explore non-Backbone-based annotations?  Or should we take that on since we plan to make use of it?

**Comment by danielweck** [comment]
Fixed: https://github.com/readium/readium-shared-js/pull/212
