### ISSUE TITLE
Highlighting CSS class name "highlight" conflicts with commonly-used CSS class name

### ISSUE THREAD

**Issue by jdempcy** [readium/readium-shared-js#203]
This issue has been reported to us by Ivan Herman of the W3C:

"There seems to be a bug in the Chrome extension. The following happens: there is a \<pre\> element in the XHTML file that has several class names, one of them is "highlight". (The content of the \<pre\> is actually coloured code.). On Readium (and not on Chrome or on iBook reader) this goes wild: the content of \<pre\> overlaps somehow with the text, is barely visible, some background colour appears, etc. If I remove the 'highlight' classname, or rename it to 'foo', everything is fine. That really smells bug to me, as if Readium had some built-in behaviour with 'highlight', and that clashed with the rest…"

I've confirmed that we are indeed using the "highlight" class name:

    .highlight {
        position: absolute;
        /* ... */
    }

We are also using "comment" and "bookmark" which may also be commonly used.

I recommend that we add a suitable prefix to CSS class names like this, for instance:

    .highlight  ==>  .readium-highlight
    .comment  ==>  .readium-comment
    .bookmark  ==>  .readium-bookmark

**Comment by jdempcy** [comment]
In readium-plugin-annotations.js:

    el : "<div class='highlight'></div>",


In annotations.css:

    .highlight {
        /* ... */
    }

In each of these locations, the word "highlight" can be changed to something like "readium-highlight" to fix potential naming collisions with ebooks that use the class name "highlight." And likewise, we can update these files for "comment" and "bookmark" as well.

**Comment by danielweck** [comment]
I could not agree more with your suggestions.
The "annotations" plugin is out-of-date, but thankfully @JCCR has started to work on it, see:
https://github.com/readium/readium-shared-js/issues/201

**Comment by iherman** [comment]
@danielweck @jdempcy : thanks!

**Comment by rkwright** [comment]
I agree with this approach.

**Comment by danielweck** [comment]
Note that in addition to the `comment`, `bookmark` and `highlight` CSS classes, there are also:
`hover-comment`, `hover-highlight`, `hover-underline`, `underline-range`, `underline-part`, `transparent-part`, `bookmark-marker`, `cfi-marker`, `range-start-marker`, and `range-end-marker` (which are obviously less problematic in terms of possible collisions with EPUB-authored class names, but I would suggest using a consistent naming convention nonetheless).
See:
https://github.com/readium/readium-shared-js/blob/develop/plugins/annotations/annotations_module.js#L972

On that basis also  (i.e. not so much because of the risk of collision, but for consistency purposes), I would recommend prefixing the `id` attribute values as well.

**Comment by danielweck** [comment]
This is fixed in @JCCR 's highlight plugin branch (which is now merged into intel-CFI-improvements)

**Comment by danielweck** [comment]
Fixed: https://github.com/readium/readium-shared-js/pull/212
