### ISSUE TITLE
How to generate readium-share-js_all.js ?

### ISSUE THREAD

**Issue by romaingiard** [readium/readium-shared-js#223]
Hello,

I'm new in Readium, I'd like to use functions like getCurrentSelectionCfi , addHighlight (now in reader_view.js)  how to include it in readium-share-js_all.?

Thanks

**Comment by danielweck** [comment]
Hello, the process is documented in the README:
https://github.com/readium/readium-shared-js/blob/develop/README.md#development
(scroll down to the "Plugins integration" section)
Make sure to include the "annotations" plugin in order to have it included in your build.
Note that this plugin is obsolete, and a revised / improved version is being worked on:
https://github.com/readium/readium-shared-js/pull/212
