### ISSUE TITLE
navigator.epubReadingSystem is not available for the publication

### ISSUE THREAD

**Issue by mmenu-mantano** [readium/readium-shared-js#227]
`globals.js` states:

> This is default implementation of reading system object that will be available for the publication's javascript to analyze at runtime.

However, I can't access the epubReadingSystem object from my publication, unless I do something like this in the web inspector:

```<iframe>.contentWindow.navigator.epubReadingSystem = navigator.epubReadingSystem;```

**Comment by danielweck** [comment]
Is that with one of Readium's own native application launchers (iOS, OSX, Android), or with Readium's own Chrome extension, or cloud / web reader?
Or is that with your own application?
I ask because the `navigator.epubReadingSystem` injection method is highly-dependent on the target platform (due to web view / web browser restrictions).

**Comment by mmenu-mantano** [comment]
@danielweck It was in our host app. I just checked with the SDKLauncher-iOS and it seems to inject the epubReadingSystem through RDPackageResourceConnection.

Unfortunately when I integrated Readium, RDPackageResourceConnection was part of the launcher and I kept my own copy until today.

Thank you for you help, closing the issue!
