### ISSUE TITLE
Fixed layout book is clipped almost entirely

### ISSUE THREAD

**Issue by rkwright** [readium/readium-shared-js#285]
Bavinder Singh wrote (via rkwright@readium.org)
"Previously in older version of Readium, all of our e-Books (fixed layout) was worked fine. But now it's not working in new version.Please check and suggest."

**Expected**:
Should render the document fine.

**Observed**:
Page is almost entirely clipped except the very top 20 pixels or so.  Appears to be placed correctly - just clipped.

**Steps to Reproduce:**
1. Load sample file [here](https://github.com/readium/readium-test-files/blob/master/issue-files/shared-js/285/TJGuide2015_v1.epub)
2. See that each page is clipped.

Reproduced in 2.23.0-alpha on OSX 10.11.  Works fine in iBooks (v. 1.5) on OSX.

**Comment by JCCR** [comment]
I think this bug was triggered when we changed the way we scale the iframes in fixed layout books.

A work around fix is to set the html element's height to an explicit value of 100%.

**Comment by rkwright** [comment]
Unfortunately, telling authors to change their output (or their tool's output) isn't going to work.  We need to figure out what we broke.

**Comment by danielweck** [comment]
Unfortunately, in this fixed-layout publication the HTML files have zero-height for both the `html` and `body` elements, even in vanilla web browsers (i.e. irrespective of the scaling transform that Readium applies). This is easy to check using the web inspector's CSS tools.

Adding `height:100%` to the HTML via Readium's layout engine (alongside the existing CSS 2D scale transform) *seems* to work, but it's a hack in the sense that we do not fully understand the browser quirk that breaks Readium's iframe + HTML-scale rendering mechanism.
Other techniques like `overflow:visible` may also "work", but I am concerned that although the content is displayed, the zero-height on container / ancestor DOM elements may trip-up behaviours that are sensitive to the CSS box model (like annotations, gestures, etc.).

At any rate, this kind of automatically-generated fixed-layout publication is probably not uncommon , so we need to find a workaround. I suggest that we check the CSS computed style (width, height values) when applying `height:100%` and HTML and BODY (to compare with the expected values when the scale ratio is applied to the meta>viewport), and that this does not introduce regression bugs  in content that has correct HTML/BODY heights to start with, or in native webviews (especially Android version <= 4.4 Kitkat, where I've seen many weird rendering bugs).

**Comment by rkwright** [comment]
As noted above, this works fine in iBooks.  Do we have any idea why it works there?

**Comment by matwood** [comment]
Based on our limited research into iBooks, it appears to ignore much of the formatting from the EPUB and apply its own. Given all the problematic EPUBs we have come across we have debated doing something similar.

**Comment by danielweck** [comment]
It works in iBooks because they set the `style` attribute for the HTML root element (of fixed-layout spine items) to `width: WWpx; height: HHpx;`, where `WW` and `HH` are the same values as given by `<meta name="viewport" content="width=WW, height=HH" />`. Page scaling is not performed at the HTML level (unlike Readium), probably in the native webview container instead. PS: the body height is zero in iBooks, they just fix the HTML height via the style attribute.

At any rate, although using `height:100%` on the root HTML element in Readium works fine (alongside the CSS scale transform), I would prefer if we injected the actual dimensions (content authors are supposed to specify the dimensions not only in meta-viewport, but also in body CSS...when the latter is missing, that's an edge-case Readium needs to address).

**Comment by danielweck** [comment]
Ah, actual W/H dimensions cause content that contains overflow:auto (like this one) to produce scrollbars. Reproducible in all major browsers. Damn! So let's use percentages.

**Comment by danielweck** [comment]
Ah, gotta love CSS! The `min-width/height` trick actually works when used with viewport dimensions. I'm double-checking with other web browsers...

**Comment by danielweck** [comment]
Fixed here:
https://github.com/readium/readium-shared-js/commit/1a70c0b31ae39b56714d282a7b8c261b7328f80b

Tested for regression bugs with fixed-layout EPUBs that used to work fine. The only significant change is the `min-width/height` on the root HTML element ; alongside the existing CSS scale transform ; which tricks the browser / webview into rendering the whole visible surface (setting 100% actually generates random width/height depending on actual DOM / CSS content, and setting width/height instead of min- equivalents results in undesired scroll bars because of overflow:auto, as is the case with the sample EPUB in this issue).

The unscaled meta-viewport width/height is enforced on body, just as most authored FXL content already does out-of-the-box (the sample in this particular issue does not). See http://www.idpf.org/epub/31/spec/epub-contentdocs.html#sec-fxl-icb-html

I'm updating Readium's "content mods" wiki page: https://github.com/readium/readium-shared-js/wiki/ContentModifications#fixed-layout-fxl

**Comment by danielweck** [comment]
As promised, I updated the wiki documentation: https://github.com/readium/readium-shared-js/wiki/ContentModifications#scaling

**Comment by rkwright** [comment]
Thanks Daniel.  I'll follow up with the use to see if I can find out which tool was used to author it.  Not given in the metadata.

**Comment by rkwright** [comment]
Got a reply from the user:

Thanks for the update.

I have created in-house Automation Tool for EPUB (Window Application and Linux App for web). Using this, I can able to convert from PDF to ePub3. This will give me very accurate (99%) output and save lot of manual production hours. It's good for complex fixed layout including math books. Conversion is 100% error free and compatible with Ipad, Google Play Book.

We also did some testing and launch sub standard tool as web service for free conversion. 

http://pdf2epub.boosez.com/

We face financial crunch so plan to close web service in a month due to server costs.
