### ISSUE TITLE
Font loader not working properly on Apple platforms

### ISSUE THREAD

**Issue by olivierkorner** [readium/readium-shared-js#300]
#### Expected Behaviour

FontLoader callback should be called when the embedded fonts used in the spine item are loaded, triggering layout and pagination update in reflowable view.
#### Observed behaviour

FontLoader fails to detect if and when fonts are loaded and instead times out after 1.5 seconds, delaying page rendering.
#### Steps to reproduce
1. Open a reflowable EPUB with embedded fonts 
2. Go to a chapter using these fonts
3. Wait 2 seconds for the page to display...
#### Test file(s)

I can share some test EPUBs privately by email.
### Product
- Readium cloud reader app
  - develop
  - Safari
  - Mac OS X (probably iOS too but not tested)
- Native application (Readium SDK C++)
  - Any native app 
  - iOS, OS X
#### Additional information

Works fine in Chrome or Firefox

**Comment by rkwright** [comment]
@olivierkorner Can you send me one of the sample files? I will also test on my end with one of mine.  Are the fonts obfuscated?

**Comment by danielweck** [comment]
+ @JCCR 
See:
https://github.com/readium/readium-shared-js/pull/179/files
https://github.com/readium/readium-shared-js/pull/244/files

**Comment by danielweck** [comment]
Default timeout is indeed 1.5s
https://github.com/readium/readium-shared-js/pull/179/files#diff-0bccb654123a1e8f4ed3ccb175c99639R211
```javascript
var FontLoaderWrapper = function($iframe, options) {
options = options || {};
options.timeout = options.timeout || 1500;
```

**Comment by danielweck** [comment]
FontLoader: https://github.com/smnh/FontLoader

**Comment by danielweck** [comment]
FYI, in the "Open Dyslexic / Custom Fonts" feature branch started by @derekriemer I implemented changes to the `FontLoader` integration strategy, in order to handle "dynamic" font-face loading when the user picks a font-family from the options list (as opposed to just "waiting for fonts" immediately after the `iframe@src` is set). I wired-up the `link@href` "onload" event as well (to detect CSS file load completion), in order to deal with network latency in the cloud-reader scenario (in my tests, this was not so much an issue when running a local HTTP server, as expected). However, this only checks injected `link@href` for custom fonts, not authored font-face declarations in EPUB stylesheets. I tested on Chrome, Firefox, Internet Explorer and Edge (not Safari OSX / iOS, and not Android browsers / webviews)

https://github.com/readium/readium-shared-js/pull/301/files#diff-103715cf0e3db43f218c7235fd2a18fb

I am not sure yet about the impact of this change on authored font-faces. I need to run further tests.

**Comment by JCCR** [comment]
I have noticed warnings coming from https://github.com/smnh/FontLoader about the size watcher on Apple devices

**Comment by olivierkorner** [comment]
Native Font Loading API is coming to Webkit:
https://webkit.org/blog/6643/improved-font-loading/

**Comment by danielweck** [comment]
Fixed in the `develop` branch, see PR https://github.com/readium/readium-shared-js/pull/308
