### ISSUE TITLE
Internal Links not working on Android WebView version 59.0.3071.125

### ISSUE THREAD

**Issue by JGuillet** [readium/readium-shared-js#398]
#### Related issue(s) and/or pull request(s)
See also issue 121 of project SDKLauncher-Android

#### Expected Behaviour
When an epub contain an internal link to another page (something like, <a href="pageX.xhtml#_anchorY"></a>, a clic on this link should go to the page at the given anchor.

#### Observed behaviour
Instead, nothing happens. It works well on previous WebView versions, but the target page is never opened.

#### Steps to reproduce
1. Have an epub with internal links
2. Open the epub on an Android webview reader with readium-shared-js
3. Clic on an internal link
4. Nothing happen

### Product
* ePub reader Android application which use readium shared-js and android readium sdk

#### Additional information
I made a few tests and it seems to come from the file readium-shared-js/js/views/internal_links_support.js, at the end of the file in the method processLinkElements.
If I comment the line 'clickEvent.preventDefault();' at the end of the method, the target page is opened, but it cause some trouble interacting with the Android part. I'm a beginner on JS so can't tell more about this.

**Comment by danielweck** [comment]
See also: https://github.com/readium/SDKLauncher-Android/issues/121

**Comment by danielweck** [comment]
webview Chromium version 58.0.3029.83 or 59.0.3071.125 ?

**Comment by JGuillet** [comment]
I had the bug on Webview version 59.0.3071.125. I didn't test it on version 58.0.3029.83.

**Comment by fjansen** [comment]
I've the same bug. It's very problematic, our epub have many internal link. Have you got any solution ?

**Comment by llemeurfr** [comment]
It seems that the issue happens when one activates a **second** link, referencing the **same** target page. @fjansen can you confirm?

**Comment by fjansen** [comment]
I don't know.
When a link has a target in the same html file, nothing happens when I click on this link. And after nothing work fine, I can't turn pages,...

**Comment by fjansen** [comment]
No news ? It's very problematic for us. And we use the 0.27 version, i hope the solution will be report in this version, not in 0.28.

**Comment by JCCR** [comment]
@fjhansen Hello, I'd like to help. I haven't been able to reproduce the issue yet with a simple testing app that I made with a WebView running the readium-js-viewer.

I'm having troubles compiling the Android Readium SDK launcher project right now. Running into something like in this issue,
https://github.com/readium/SDKLauncher-Android/issues/123

It would also be helpful if you could email me a sample of an EPUB that is experiencing the faulty links.

You can email at: juanc@evidentpoint.com

**Comment by fjansen** [comment]
I've send you an epub test with two internal links.
Thank you Juan

**Comment by danielweck** [comment]
There's a minimal "internal linking" sample file at the `readium-js-viewer` repository:
https://github.com/readium/readium-js-viewer/blob/develop/epub_content/internal_link.epub

**Comment by danielweck** [comment]
So according to @JGuillet the `preventDefault()` behaviour is the culprit (see code at https://github.com/readium/readium-shared-js/blob/27987760a4cfec2027379a00735b0e9d9aebbc48/js/views/internal_links_support.js#L217 )

...and according to @nimisis this is a regression bug from Android's webview `58.0.3029.83` to `59.0.3071.125` (see https://github.com/readium/SDKLauncher-Android/issues/121 ).

**Comment by danielweck** [comment]
Repro test:
https://readium.firebaseapp.com/?epub=https%3A%2F%2Fcdn.rawgit.com%2FIDPF%2Fepub3-samples%2Fmaster%2F30%2Fwasteland&goto=%7B%22idref%22%3A%22t1%22%2C%22elementCfi%22%3A%22%2F4%2F4%5Bbodymatter%5D%2F6%5Bch3%5D%2F28%2F2%5Bln308%5D%2F1%3A0%22%7D

Locate line 310 which says "O Lord Thou pluckest". The 3 lines above end with clickable asterisk. They navigate into the notes section at the end of the same document, and there are even back-links to reach the original location. This works fine in Chrome and Safari on OSX. Now testing Android...

**Comment by danielweck** [comment]
Linking works fine using the above test URL (Wasteland with footnotes back-forth navigation) in Chrome web browser (61.0.3163.98) on Android 8.0.0 (Oreo). I tried both single and two-page spread.

Can anybody else test?
Is the reported bug reproducible in webview  or web browser?

**Comment by danielweck** [comment]
Interestingly, `58.0.3029.125` is the version reported by https://play.google.com/store/apps/details?id=test.webview.com.br.webviewtest on my phone.
I'm not sure whether this is:
https://play.google.com/store/apps/details?id=com.google.android.webview
or:
https://play.google.com/store/apps/details?id=com.android.chrome
(which shares its webview component, system-wide)

**Comment by danielweck** [comment]
My "developer options" tell me the Android System Webview (version `58.0.3029.125`) is disabled, probably because I have Google Chrome installed (version `61.0.3163.98`).

So, I need to figure-out how to test Android System Webview version `59.0.3071.125` as per the bug report. I suppose I could temporarily disable Chrome to see if Android reverts to its auto-updatable APK?

See attached screenshot.
![androidsystemwebview_chrome](https://user-images.githubusercontent.com/625201/31044292-88579406-a5c4-11e7-8f07-b0836de90019.png)

**Comment by danielweck** [comment]
Yep, I disabled the Chrome app, which then allowed me to update the Android System Webview (as it automatically became enabled). Version `61.0.3163.98` is the version now reported by https://play.google.com/store/apps/details?id=test.webview.com.br.webviewtest (which matches exactly the latest Chrome app version).
So, to conclude I am *not* able to reproduce the bug, probably because I am not able to install / use version `59.0.3071.125`?

**Comment by fjansen** [comment]
Daniel, I've the same version of Chrome and Android Systeme Webview : 61.0.3163.98. And I've got the bug.
The bug is here sine v59 of Android System Webview.

**Comment by danielweck** [comment]
@fchasen do you mean that the internal links do not work correctly in the aforementioned EPUB sample:
https://github.com/readium/readium-shared-js/issues/398#issuecomment-333290569
?
..because everything works fine at my end, so perhaps the bug is specific to a particular HTML / CSS design pattern.

**Comment by fjansen** [comment]
Yes, i've this epub in the lcp launcher, synchronised in may/june. The links in the same file doesn't work. The version of shared js is 0.27-alpha

**Comment by fjansen** [comment]
... and after a click on internal link, i can't turn pages.

**Comment by danielweck** [comment]
what are the error messages in the remote Chrome webview debug console?
(the fact that you cannot turn pages means that Readium's internal state is somehow broken)

**Comment by fjansen** [comment]
There's no error in the console. That's why i've problem to debug and help you on this fonctionnality.

**Comment by fjansen** [comment]
I've test again with the launcher branch LCP (shared js version 0.27-alpha) i've install in may, and the internal links are not working. No error in the remote chrome webview debug console.
I've install the last lancher branch develop (shared js version 0.28-alpha), internal links are not workink too. But in the console i've a error message the second time i click on a link : Illegal pageIndex value:  12 column count is  9   readium-shared-js_all.js:43086
@danielweck you don't have any problem whith internal link ?
I send you my test file. The internal links are in the "Chapitre introductif" file.
[internal_link.zip](https://github.com/readium/readium-shared-js/files/1355742/internal_link.zip)

**Comment by fjansen** [comment]
I've complete my test and install old version of shared js. I've the same issue with 0.26 and 0.25 version of shared js.
With 0.24 version nothing work, the epub is not rendered.
Since 59 version of "Android System Webview", only 0.25 and newer version of shared js render epub.

**Comment by fjansen** [comment]
@danielweck this issue is in Android Launcher, not in Chrome.
I've test the url in the repro test with Chrome app on Android and it's work, no problem. But it doesn't work in the launcher.

**Comment by danielweck** [comment]
I think I found the source of the problem: the Underscore debouncer function is broken in the webview setup used by the Android SDK launcher app. No idea why, but removing the debouncer fixes the problem. I am investigating further.

**Comment by danielweck** [comment]
If I change the default trailing debouncer to a leading one, then the links work, but page turn is broken...looks like one of those weird browser-specific setTimeout() (defer) bugs.

**Comment by danielweck** [comment]
In fact, any setTimeout() callback inside the click() event handler is "ignored" (callback never called). As the debouncer uses setTimeout() to schedule the function call later in the execution stack, no wonder why things are broken! Very strange bug!

**Comment by danielweck** [comment]
Damn!!
For some strange reason, in this particular Android launcher app (i.e. not in the web browsers) when `setTimeout()` is invoked inside a DOM event listener (e.g. link clicks) for an iframe-hosted document, the callback is not called, unless the timeout function is explicitly called on the iframe's own window instance (not the top-frame global).

Here's a reduced repro case:
```javascript
    this.processLinkElements = function($iframe, spineItem) {
        var epubContentDocument = $iframe[0].contentDocument || $iframe[0].contentWindow.document;

		var aElements = epubContentDocument.getElementsByTagName("a");
		if (!aElements.length) {
			aElements = epubContentDocument.getElementsByTagName("A");
		}
		console.log(aElements);
		console.log(aElements.length);
		
		for (var i = 0; i < aElements.length; i++) {
		    
			var aElement = aElements[i];
			if (!aElement.getAttribute("href")) {
				console.log("no href");
				continue;
			}
			console.log(aElement);
			console.log(i);
			
			aElement.addEventListener("click", function(clickEvent) {
				console.log("USE CAPTURE");

				$iframe[0].contentWindow.setTimeout(function() {
					console.log("USE CAPTURE -- TIMEOUT");
				}, 500);
			}, true);
			
			aElement.addEventListener("click", function(clickEvent) {
				console.log("USE BUBBLING");

				$iframe[0].contentWindow.setTimeout(function() {
					console.log("USE BUBBLING -- TIMEOUT");
				}, 500);
			}, false);
		}
    }
```

If we change `$iframe[0].contentWindow.setTimeout` to `setTimeout`, then the callbacks are never called!
The problem is that there are lots of implicit / indirect calls to setTimeout() on the global window instance, for example via _.defer() or _.debounce() (which is why I mentioned the latter in my earlier comments, as I noticed the broken debouncer while debugging).

@JCCR, are you familiar with this kind of thing?

**Comment by danielweck** [comment]
PS: I am assuming the Content Security Policy has changed since the last time links worked fine with the Android webview. Any tips about testing various combinations of CSP settings? Maybe on the iframe itself?

**Comment by fjansen** [comment]
Ok, it's the same problem i've found in my extra code. I've some jquery rules using setTimeout() and the callback is never called.

**Comment by danielweck** [comment]
Realistically, we cannot ; without significant refactoring ; modify all the `readium-shared-js` code that directly or indirectly invokes `setTimeout()` (e.g. `_.defer()`, `_.debounce()`, `_.throttle()`), in order to ensure that the correct `window` global is used to prefix the calls (i.e. window of the top-level `reader.html` frame vs. iframe(s) that host EPUB content documents).

The problem is: all the control logic implemented by `readium-shared-js` that affects the DOM of iframe-hosted documents actually lives in the top-level `reader.html` window context (i.e. the Android webview). For example: link handling (this issue), highlights, Media Overlays audio playback, etc. In other words, iframe content is manipulated by the iframe's parent.

So when an event originates from the iframe's document (e.g. link click handler) and when the event listener is registered by the parent, the event callback function is executed in the context where `readium-shared-js` lives. This has always worked (and continues to work fine in all platforms, it seems), but for some reason in the newer Android's webview, `setTimeout()` callbacks are not placed in the local execution stack (i.e. not executed) anymore.

So, this is either the correct behaviour (not a regression bug per se, but a webview fix / CSP feature that will at some point be implemented everywhere else, e.g. iOS), or this is actually a regression bug for which we need a workaround. Or, I am missing something totally obvious and I am wasting everyone's time ;)

I suggest "we" (anybody with spare time ... i.e. not me at the moment) create a minimal repro app to demonstrate the behaviour outside of Readium.

Another option is to examine the WebView settings we currently use, and see if some CSP (or related) parameters fix this situation:
https://github.com/readium/SDKLauncher-Android/blob/438da1ede63fa5146153352b9322e454854b550a/SDKLauncher-Android/app/src/main/java/org/readium/sdk/android/launcher/WebViewActivity.java#L304-L314

Any other ideas?

**Comment by fjansen** [comment]
Daniel, i attach simple html/js code. Is it a correct exemple ?
I've make a little Android app with a webview and this files, all work.

[assets.zip](https://github.com/readium/readium-shared-js/files/1368494/assets.zip)

**Comment by JCCR** [comment]
@danielweck 
@fjansen 
I finally got the Android app to build! The missing piece was that for some reason I was using NDK 16 and it wasn't working well with the most basic header includes and GCC. Using NDK 14 via manual download and pointing it with ndk.dir in local.properties got it to compile. 

I tried it out.. I couldn't reproduce the problem using my simple Android App with a webview
```kotlin
    @SuppressLint("SetJavaScriptEnabled")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_fullscreen)

        webView1.webViewClient = object : WebViewClient() {
            override fun shouldOverrideUrlLoading(view: WebView, url: String): Boolean {
                return false
            }
        }

        webView1.settings.javaScriptEnabled = true
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
            webView1.settings.allowUniversalAccessFromFileURLs = true
        }
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
            webView1.settings.mediaPlaybackRequiresUserGesture = false
        }
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
            WebView.setWebContentsDebuggingEnabled(true)
        }

    }

    override fun onPostCreate(savedInstanceState: Bundle?) {
        super.onPostCreate(savedInstanceState)
        webView1.loadUrl("http://10.10.14.108:8080/dev/index_RequireJS_no-optimize.html?epub=..%2Fepub_content%2Finternal_link&goto=%7B%22idref%22%3A%22file_161282.xhtml%22%2C%22elementCfi%22%3A%22%2F4%2F2%2F2%5Bbrick_161282%5D%2F2%2F2%2F1%3A0%22%7D&")
    }
```
As you can see I load my own Readium web instance in the URL there.

I used the SDKLauncher-Android app and loaded @fjansen's internal_link test EPUB just like in my local Readium web instance.  I *did* have the issue reproduced there.

I made SDKLauncher-Android load my URL instead of org/readium/sdk/android/launcher/WebViewActivity.java:262 `mWebview.loadUrl(READER_SKELETON);`
It loaded my Readium web instance and I did *not* experience the issue.

---
My theory at the moment is this has to do something with the reader.html bootstrapping page being loaded from the `file://` protocol, which has special security rules based from experience.

**Comment by danielweck** [comment]
Yeah, regarding NDK 14, 15, 16 .... I am facing other problems too:
https://github.com/readium/readium-lcp-client/issues/42

**Comment by danielweck** [comment]
@JCCR I suspect that if `reader.html` is served from another HTTP domain (ip + port) as the iframe's documents, some of the readium-shared-js Javascript will fail to interact / modify the DOM, due to implicit sandboxing / security rules for embedded content. That's the reason why `file://` has been very convenient. We could also serve `reader.html` on the exact same ip+port, but the iframe documents will then be able to access the parent content (reader.html) which potentially opens the door to malicious side-loaded publications.
Thoughts?

**Comment by danielweck** [comment]
Another important distinction is that 
`webView1.loadUrl("http://10.10.14.108:8080/dev/index_RequireJS_no-optimize.html?epub=..%2Fepub_content%2Finternal_link&goto=%7B%22idref%22%3A%22file_161282.xhtml%22%2C%22elementCfi%22%3A%22%2F4%2F2%2F2%5Bbrick_161282%5D%2F2%2F2%2F1%3A0%22%7D&")`
loads the cloud reader into the webview, which in turn loads EPUB HMTL documents into the embedded iframe via BlobURI, not via a direct HTTP link (unlike `reader.html`'s operating mode).
See `useSimpleLoader`:
https://github.com/readium/readium-js-viewer/blob/135842b6381391116f5d9ed5cf40dfe62822ea4c/src/cloud-reader/index.html#L99
https://github.com/readium/readium-js/blob/develop/js/epub-fetch/iframe_zip_loader.js
vs. the Chrome app:
https://github.com/readium/readium-js-viewer/blob/135842b6381391116f5d9ed5cf40dfe62822ea4c/src/chrome-app/requirejs-config.js#L53
https://github.com/readium/readium-shared-js/blob/develop/js/views/iframe_loader.js
vs. the native apps which invoke `new ReaderView()` directly:
https://github.com/readium/readium-shared-js/blob/62490d18031c6dd675639b442a7b791274bfe7b1/js/views/reader_view.js#L92

**Comment by danielweck** [comment]
FYI
I fixed the problem by simulating the HTTP ip + port domain for reader.html and associated resources (i.e. the whole readium-shared-js bundle). It is a trivial code fix, but there is a risk of regression bug in terms of security (as mentioned above). I am investigating further.

**Comment by danielweck** [comment]
I can confirm that the security problem exists, for instance `window.top.ReadiumSDK.reader.openPageLeft()` etc. can be invoked from the EPUB content iframe, in fact any side-loaded Javascript behaviour can be executed in the parent host context (i.e. reader.html).
However, in native iOS OSX Android launchers, the reader.html "app" is instantiated each time from scratch, so in a way it is a lesser evil than a longer-lived app instance that has access to multiple publications (e.g. cloud reader or Chrome app session).
That being said, I am still concerned that a malicious EPUB could inject more persistent behaviour via cache or localStorage, i.e. Javascript code that would load each time reader.html is launched.
Thoughts?

**Comment by rkwright** [comment]
@danielweck I understand your concern, but if we don't use that fix, what is our alternative?  More research?  Or do we now understand the problem well enough to exclude other ways of fixing it (save for wholesale refactoring)?

This reminds me of the[ inline-script issue ](https://github.com/readium/readium-js-viewer/issues/615) that arose with the release of Chrome 57. However, in that case there was not way around it save rewriting thousands of EPUBs.  They are two different issues, obviously, but they both involve changes in the underlying browser engine that causes us serious problems.

Two questions:

- What are the chances this will crop up in iOS and will the fix you propose work there?
- Would this problem also potentially affect R2?  If so, then we (Aferdita) need to be careful to that the implementation there isn't susceptible.

**Comment by danielweck** [comment]
I've pushed the HTTP vs. file:// fix in the develop branch, so that you guys can test this as soon as possible:
https://github.com/readium/SDKLauncher-Android/commit/aea1cea4bbcc43946f2783f07407d31f09bcbb88
Please bear in mind the aforementioned security caveat!

**Comment by danielweck** [comment]
@rkwright I suspect other Chromium-based platforms may be affected, such as Electron. In fact, the readium-desktop app (navigator part) which I am working on also has a root file://index.html and embedded frames to host EPUB content. However, the sandboxing in my implementation is a lot more strict: I use the webview tag instead of HTML iframe elements, in order to isolate publication HTMLs into their own separate processes, and I rely on Electron-specific APIs to inject behaviour into spine items, manipulate DOM etc.

**Comment by danielweck** [comment]
PS @rkwright (side note) remember the InDesign `window.location = "navigate to some file"` issue in Readium1? (i.e. inability to intercept all possible forms of hyperlinking / content redirection, in the Chrome app and cloud reader)
Well, with Electron (just as with native apps I suppose) I can intercept and prevent such abusive use of scripted navigation which corrupts the reading system's internal state.

**Comment by llemeurfr** [comment]
Another question is: does this issue impacts all current Readium based Android apps? I asked Helicon, they had a rtl issue with the apparition of a recent version of WebKit but none of their users rose this link issue. 

Also @fjansen, as this issue is critical for your company, could you pls test ASAP the solution proposed by Daniel and give feedback?

**Comment by llemeurfr** [comment]
Another question is: does this issue impacts all current Readium based Android apps? I asked Helicon, they had a rtl issue with the apparition of a recent version of WebKit but none of their users rose this link issue. 

Also @fjansen, as this issue is critical for your company, could you pls test ASAP the solution proposed by Daniel and give feedback?

**Comment by danielweck** [comment]
By the way, I see that GitHub says "danielweck removed the priority:Blocking label 6 minutes ago" ... but I didn't. So I guess when @llemeurfr mistakenly closed the issue (only to immediately re-open it), the "priority:blocking" was automatically removed by GitHub (?) As I am not the original poster of this issue, I guess I am the one who added the "priority:blocking" label in the first place :)  (I don't remember)

**Comment by danielweck** [comment]
Maybe Helicon's app isn't based on ReadiumSDK + readium-shared-js, but instead it is a hybrid app based on readium-js + readium-shared-js ?

**Comment by fjansen** [comment]
@llemeurfr , @danielweck the fix in android application work. 
But I've an error in chrome remote console : 
Failed to load resource: the server responded with a status of 404 (Not Found)      :8080/favicon.ico
I don't think I've this error before.

**Comment by llemeurfr** [comment]
"the fix in android application work." -> That's great! 

The 404 issue on a favicon seems a minor issue and should be processed in a different github issue.
We'll let this issue open for some days, if @JGuillet can check on his side, and will be able to close it I hope.

**Comment by danielweck** [comment]
Yes, there is a request for favicon, not sure where from. Not problematic, just garbage in the console.

**Comment by JGuillet** [comment]
Hello,
I'm sorry for being quiet since I opened the bug, I worked and other projects and didn't have time to check your fix.
I just did and it works for me, the timeout callbacks are now called correctly.
I close the issue, thank you all very much for this! Let's hope Google won't make a similar update for the webview in the future ;)
